name: Release Version

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Validate semantic version
        run: |
          if [[ ! "${GITHUB_REF_NAME}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid version format"
            exit 1
          fi

      - name: Checkout
        uses: actions/checkout@v4

      - name: Login Docker Hub
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Build versioned image
        run: docker build -t ci4-starter:${GITHUB_REF_NAME} .

      - name: Tag images
        run: |
          docker tag ci4-starter:${GITHUB_REF_NAME} ${{ secrets.DOCKER_USER }}/ci4-starter:${GITHUB_REF_NAME}
          docker tag ci4-starter:${GITHUB_REF_NAME} ${{ secrets.DOCKER_USER }}/ci4-starter:latest

      - name: Push versioned image
        run: |
          docker push ${{ secrets.DOCKER_USER }}/ci4-starter:${GITHUB_REF_NAME}
          docker push ${{ secrets.DOCKER_USER }}/ci4-starter:latest